### ISSUE TITLE
raamatute loetelu; taustamuusika

### ISSUE THREAD

**Issue by Karel4** [Pmarva/piibel#2]
Täiendasin raamatute loetelu, kust olid puudu apokrüüfid. Lisasin laulu sõnade lingi kõrvale ka taustamuusika lingi.

[index.html.txt](https://github.com/Pmarva/piibel/files/3717698/index.html.txt)

**Comment by Pmarva** [comment]
Feature added, but need your own music at specific folder
https://github.com/Pmarva/piibel/commit/56bd2e5e177b35e463ac818c76e7b4b948279e0f
