### ISSUE TITLE
tühik ja mõttekriips

### ISSUE THREAD

**Issue by Karel4** [Pmarva/piibel#3]
Äkki selles meie skriptis saab ka selle sisse panna et ala 1ms 2:2, 3 töötaks (tühikuga).
Samuti sidekriipsu asemel see pikem dash.

**Comment by Pmarva** [comment]
Added en-dash feature at search
1ms 1:1-10 with regular dash and now working also with en-dash Esr 4:1–7
Space after comma in multiple comma separated verse search 1ms 1:1, 2, 3
